baseurl = "https://useR-2018.github.io/"
languageCode = "en-us"
metadataformat = "yaml"
title = "useR! 2018"
theme = "hugo-alabaster-theme"

disqusShortname = "visnut"
googleAnalytics = ""

[params]
	name = "July 10-13, 2018"
	description = "The conference for users of R"

	github_user   = "useR-2018"
	github_repo   = "useR-2018.github.io"
	github_banner = false

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicon = "user_au_logo.png"

[params.sidebar]
	logo = "user_au_logo.png"


	github_button  = false
	travis_button  = false
	codecov_button = false
	gratipay = ""

	show_relations = true

[params.footer]
	copyright = "[R Foundation](https://www.r-project.org/foundation/)"
	show_powered_by = true
